scrape_configs:
- job_name: ' HA Cloud Session Server with TLS'
  scrape_interval: 15s
  scheme: https
  tls_config:
    insecure_skip_verify: true
  metrics_path: actuator/prometheus
  static_configs:
    - targets: ['session-server-hostname:7443'] 